version: v{build}
max_jobs: 1
configuration: Release
clone_depth: 50
image: Visual Studio 2019
before_build:
- cmd: bootstrap.bat
build:
  project: Hearthstone Collection Tracker.sln
  verbosity: minimal
artifacts:
- path: Hearthstone Collection Tracker\bin\Release\exportalas.dll
  name: Release-dll
- path: Hearthstone Collection Tracker\bin\Debug\exportalas.dll
  name: Debug-dll
